# -*- mode: ruby -*-
# vi: set ft=ruby :

    Vagrant.configure("2") do |config|
    config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.network "forwarded_port", guest: 80, host: 8888
    centos.vm.network "forwarded_port", guest: 443, host: 8443
end
    
    config.vm.provision "shell", run: "always",  inline: <<-SHELL
        setenforce 0
        sed -ie 's/^SELINUX=.*$/SELINUX=disabled/' /etc/selinux/config
        mkdir /var/www/website.com/html/
        mkdir /etc/httpd/conf.d/
        
    cp  cp -f /vagrant/www-content/index.html /usr/share/httpd/noindex/index.html
    cp  cp -f /vagrant/www-content/index.html /var/www/html
        cp -f /vagrant/ssl.conf /etc/httpd/conf.d/
        mkdir /etc/ssl/privatekey
        chmod 700 /etc/ssl/privatekey
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/pki/tls/private/domain.key -out /etc/pki/tls/certs/domain.crt -subj "/C=UA/ST=Lviv/L=Lviv/O=none/OU=none/CN=127.0.0.1"
        yum install -y epel-release
        yum install -y httpd
        yum install -y mod_ssl
        httpd -t
        systemctl start httpd
        systemctl enable httpd
                
    SHELL
  end
  
  
